// apps/starter-solidstart-blog/src/routes/index.tsx
import { createAsync, type RouteDefinition } from '@solidjs/router';
import { For, Show } from 'solid-js';

import { getPosts } from '~/lib/content.js';

export const route = {
  preload: () => getPosts(),
} satisfies RouteDefinition;

export default function Home() {
  const posts = createAsync(() => getPosts());

  return (
    <div style={{ 'font-family': 'sans-serif', 'max-width': '640px', margin: '2rem auto', padding: '0 1rem' }}>
      <h1>My Blog</h1>
      <Show when={(posts()?.length ?? 0) === 0}>
        <p>
          No posts yet. <a href="/admin">Open the CMS</a> to write your first post.
        </p>
      </Show>
      <ul style={{ 'list-style': 'none', padding: '0' }}>
        <For each={posts()}>
          {post => {
            const slug = post.key.replace(/^posts\//, '').replace(/\.md$/, '');
            return (
              <li style={{ 'margin-bottom': '1rem' }}>
                <a href={`/blog/${slug}`}>{slug}</a>
                <Show when={post.updatedAt}>
                  {' · '}
                  <time>{new Date(post.updatedAt!).toLocaleDateString()}</time>
                </Show>
              </li>
            );
          }}
        </For>
      </ul>
      <p>
        <a href="/admin">Admin →</a>
      </p>
    </div>
  );
}

// apps/starter-sveltekit-blog/src/routes/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
</script>

<h1>My Blog</h1>

{#if data.posts.length === 0}
  <p>No posts yet. <a href="/admin">Open the CMS</a> to write your first post.</p>
{:else}
  <ul>
    {#each data.posts as post (post.key)}
      <li>
        <a href={`/blog/${post.slug}`}>{post.slug}</a>
        {#if post.updatedAt}
          · <time>{new Date(post.updatedAt).toLocaleDateString()}</time>
        {/if}
      </li>
    {/each}
  </ul>
{/if}

<style>
  ul {
    list-style: none;
    padding: 0;
  }
  li {
    margin-bottom: 1.5rem;
  }
  a {
    color: #0070f3;
  }
  time {
    color: #666;
    font-size: 0.9em;
  }
</style>
