// apps/starter-sveltekit-blog/src/routes/blog/[slug]/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';

  let { data }: { data: PageData } = $props();
</script>

<article>
  <h1>{data.title}</h1>
  {#if data.date}
    <time style="color:#666">{new Date(data.date).toLocaleDateString()}</time>
  {/if}
  {#if data.description}
    <p><em>{data.description}</em></p>
  {/if}
  <!-- body is raw markdown; pipe through remark/unified in production -->
  <pre style="white-space:pre-wrap;font-family:inherit">{data.body}</pre>
</article>

<p><a href="/">← Back</a></p>

// apps/starter-nuxt-d1/pages/blog/[slug].vue
<script setup lang="ts">
const route = useRoute();
const slug = route.params.slug as string;

const { data: post, error } = await useFetch(`/api/posts/${slug}`);
if (error.value) throw createError({ statusCode: 404 });
</script>

<template>
  <div>
    <Head>
      <Title>{{ (post as any)?.title ?? slug }}</Title>
    </Head>

    <article v-if="post">
      <h1>{{ (post as any).title ?? slug }}</h1>
      <time v-if="(post as any).date">{{ new Date((post as any).date).toLocaleDateString() }}</time>
      <p v-if="(post as any).description"><em>{{ (post as any).description }}</em></p>
      <pre style="white-space:pre-wrap;font-family:inherit">{{ (post as any).body }}</pre>
    </article>

    <p><NuxtLink to="/">← Back</NuxtLink></p>
  </div>
</template>
