// apps/starter-react-router-blog/app/root.js
import { Links, Meta, Outlet, Scripts, ScrollRestoration } from 'react-router';
import { jsx as _jsx, jsxs as _jsxs } from 'react/jsx-runtime';
export function Layout({ children }) {
  return (_jsxs('html', {
    lang: 'en',
    children: [
      _jsxs('head', {
        children: [
          _jsx('meta', { charSet: 'utf-8' }),
          _jsx('meta', { name: 'viewport', content: 'width=device-width, initial-scale=1' }),
          _jsx(Meta, {}),
          _jsx(Links, {}),
        ],
      }),
      _jsxs('body', { children: [children, _jsx(ScrollRestoration, {}), _jsx(Scripts, {})] }),
    ],
  }));
}
export default function App() {
  return _jsx(Outlet, {});
}

// apps/starter-qwik-blog/src/root.tsx
import { component$ } from '@builder.io/qwik';
import { QwikCityProvider, RouterOutlet, ServiceWorkerRegister } from '@builder.io/qwik-city';

export default component$(() => {
  return (
    <QwikCityProvider>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Qwik Blog</title>
        <RouterHead />
      </head>
      <body lang="en">
        <RouterOutlet />
        <ServiceWorkerRegister />
      </body>
    </QwikCityProvider>
  );
});

const RouterHead = component$(() => {
  return null;
});
