// apps/starter-next-pages/src/pages/_app.tsx
import type { AppProps } from 'next/app';
import Link from 'next/link';

export default function App({ Component, pageProps }: AppProps) {
  return (
    <div
      style={{
        fontFamily: 'system-ui, sans-serif',
        maxWidth: 720,
        margin: '0 auto',
        padding: '2rem 1rem',
        lineHeight: 1.6,
      }}
    >
      <header style={{ marginBottom: '2rem' }}>
        <Link href="/" style={{ textDecoration: 'none', color: 'inherit' }}>
          <h1 style={{ margin: 0 }}>LaikaCMS blog</h1>
        </Link>
        <nav style={{ marginTop: '0.5rem' }}>
          <Link href="/" style={{ marginRight: '1rem' }}>Home</Link>
          <Link href="/admin">Admin</Link>
        </nav>
      </header>
      <main>
        <Component {...pageProps} />
      </main>
    </div>
  );
}

// apps/starter-vite-solid-spa/src/App.tsx
import { A } from '@solidjs/router';
import type { ParentProps } from 'solid-js';

export function App(props: ParentProps) {
  return (
    <>
      <header style="margin-bottom: 2rem;">
        <A href="/" style="text-decoration: none; color: inherit;">
          <h1 style="margin: 0;">LaikaCMS blog</h1>
        </A>
        <nav style="margin-top: 0.5rem;">
          <A href="/" style="margin-right: 1rem;">Home</A>
          <a href="/admin">Admin</a>
        </nav>
      </header>
      <main>{props.children}</main>
    </>
  );
}
