// apps/starter-waku-turso/src/pages/index.tsx
import { collectStream } from 'laikacms/compat';

import { laika } from '../laika.js';

export default async function HomePage() {
  const { items: records } = await collectStream(
    laika.documents.listRecordSummaries({
      pagination: { page: 1, perPage: 100 },
      folder: 'posts',
      depth: 1,
      type: 'published',
    }),
  );

  type Summary = { type: string, key: string, updatedAt?: string };

  const posts = (records as Summary[])
    .filter(r => r.type === 'published-summary')
    .sort((a, b) => {
      if (a.updatedAt && b.updatedAt) return b.updatedAt.localeCompare(a.updatedAt);
      return b.key.localeCompare(a.key);
    });

  return (
    <main>
      <h1>My Blog</h1>
      {posts.length === 0
        ? (
          <p>
            No posts yet. <a href="/admin">Open the CMS</a> to write your first post.
          </p>
        )
        : (
          <ul style={{ listStyle: 'none', padding: 0 }}>
            {posts.map(post => {
              const slug = post.key.replace(/^posts\//, '').replace(/\.md$/, '');
              return (
                <li key={post.key} style={{ marginBottom: '1.5rem' }}>
                  <a href={`/blog/${slug}`} style={{ color: '#0070f3' }}>{slug}</a>
                  {post.updatedAt && (
                    <>
                      {' · '}
                      <time style={{ color: '#666', fontSize: '0.9em' }}>
                        {new Date(post.updatedAt).toLocaleDateString()}
                      </time>
                    </>
                  )}
                </li>
              );
            })}
          </ul>
        )}
      <p>
        <a href="/admin" style={{ color: '#888' }}>Admin →</a>
      </p>
    </main>
  );
}

// apps/starter-nuxt-blog/pages/index.vue
<script setup lang="ts">
/**
 * Blog homepage — lists published posts via GET /api/posts.
 *
 * useFetch runs server-side during SSR and client-side during navigation,
 * so the list is always fresh. The key is stable so Nuxt deduplicates the fetch.
 */
const { data: posts } = await useFetch('/api/posts');
</script>

<template>
  <div>
    <Head>
      <Title>My Blog</Title>
    </Head>

    <h1>My Blog</h1>

    <p v-if="!posts || posts.length === 0">
      No posts yet. <NuxtLink to="/admin">Open the CMS</NuxtLink> to write your first post.
    </p>

    <ul v-else style="list-style:none;padding:0">
      <li v-for="post in posts" :key="post.slug" style="margin-bottom:1.5rem">
        <NuxtLink :to="`/blog/${post.slug}`">{{ post.slug }}</NuxtLink>
        <span v-if="post.updatedAt">
          &nbsp;·&nbsp;<time>{{ new Date(post.updatedAt).toLocaleDateString() }}</time>
        </span>
      </li>
    </ul>
  </div>
</template>
