// apps/starter-qwik-blog/src/routes/posts/[slug]/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$ } from '@builder.io/qwik-city';

import { runTask } from 'laikacms/compat';
import { NotFoundError } from 'laikacms/core';

import { laika } from '~/server/laika';

interface Post {
  title: string;
  body: string;
  date: string | null;
}

export const usePost = routeLoader$(async ({ params, status }): Promise<Post | null> => {
  const slug = params.slug;
  try {
    const doc = await runTask(laika.documents.getDocument(`posts/${slug}`));
    const content = ((doc as { content?: Record<string, unknown> }).content ?? {}) as Record<
      string,
      unknown
    >;
    return {
      title: (content.title as string) ?? slug,
      body: (content.body as string) ?? '',
      date: (content.date as string) ?? null,
    };
  } catch (err) {
    if (err instanceof NotFoundError) {
      status(404);
      return null;
    }
    throw err;
  }
});

export default component$(() => {
  const post = usePost();
  if (!post.value) return <p>Post not found.</p>;
  return (
    <article>
      <h2 style="margin-bottom: 0.25rem;">{post.value.title}</h2>
      {post.value.date && <small style="color: #666;">{new Date(post.value.date).toLocaleDateString()}</small>}
      <div style="margin-top: 1.5rem; white-space: pre-wrap;">{post.value.body}</div>
    </article>
  );
});

// apps/starter-waku-turso/src/pages/blog/[slug].tsx
import { runTask } from 'laikacms/compat';
import { LaikaError } from 'laikacms/core';

import { laika } from '../../laika.js';

interface PostContent {
  title?: string;
  date?: string;
  description?: string;
  body?: string;
}

export const getConfig = () => ({ render: 'dynamic' as const });

export default async function BlogPostPage({ slug }: { slug: string }) {
  let post;
  try {
    post = await runTask(laika.documents.getDocument(`posts/${slug}`));
  } catch (err) {
    if (err instanceof LaikaError) {
      return (
        <p>
          Post not found. <a href="/">← Back</a>
        </p>
      );
    }
    throw err;
  }

  const { title, date, description, body } = post.content as PostContent;

  return (
    <article>
      <h1>{title ?? slug}</h1>
      {date && <time style={{ color: '#666' }}>{new Date(date).toLocaleDateString()}</time>}
      {description && (
        <p>
          <em>{description}</em>
        </p>
      )}
      <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit' }}>{body}</pre>
      <p>
        <a href="/">← Back</a>
      </p>
    </article>
  );
}
